apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-backup
  labels:
    {{- include "lifeos.labels" . | nindent 4 }}
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: {{ .Values.backup.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.backup.storageSize }}
