"""add chat_message model column

Revision ID: d1db6691153d
Revises: 5b72d0f414c6
Create Date: 2026-07-24 09:28:06.706101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1db6691153d'
down_revision: Union[str, Sequence[str], None] = '5b72d0f414c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_message', sa.Column('model', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_message', 'model')
    # ### end Alembic commands ###
